backend:
  name: github
  repo: matthieuauger/my-blog

media_folder: static/assets
public_folder: assets

collections:
  - name: post
    label: Post
    folder: src/pages
    create: true
    fields:
      - { name: slug, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
